CREATE DATABASE IF NOT EXISTS `LampStore`;
USE LampStore;

CREATE TABLE `lamp` (
    id BIGINT NOT NULL AUTO_INCREMENT,
    power BIGINT NOT NULL,
    manufacturer VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
